# typed: false
# frozen_string_literal: true

# Generated by scripts/update-homebrew-tap.sh in onembyte/kolkrabbi.
# Do not edit by hand: regenerate it from the release's own checksums.txt.
class Kolk < Formula
  desc "Model-agnostic AI coding agent for the terminal"
  homepage "https://kolkrabbi.francomichetti.com/"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/onembyte/kolkrabbi/releases/download/v1.3.7/kolk_1.3.7_darwin_arm64.tar.gz"
      sha256 "65fa672d139491570b06db145f1d99d1e2756bc7f0c3a93723c49d608c184593"
    end
    on_intel do
      url "https://github.com/onembyte/kolkrabbi/releases/download/v1.3.7/kolk_1.3.7_darwin_amd64.tar.gz"
      sha256 "32d970e400bb84f34ae701387f4f63fa2b0b3ba49fbd2510f74fefc4ea1079ff"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/onembyte/kolkrabbi/releases/download/v1.3.7/kolk_1.3.7_linux_arm64.tar.gz"
      sha256 "577f03590d4e91bebc9d30835b1d77f572fde299ed3a1580490e8fcb3fd6a92d"
    end
    on_intel do
      url "https://github.com/onembyte/kolkrabbi/releases/download/v1.3.7/kolk_1.3.7_linux_amd64.tar.gz"
      sha256 "622bab3c95d6df78849e97627d5907a60f39fcf9795607143f9a4007f7d0e6b9"
    end
  end

  def install
    bin.install "kolk"
  end

  test do
    assert_match "kolk", shell_output("#{bin}/kolk help")
  end
end
