# typed: false
# frozen_string_literal: true

# Generated by scripts/update-homebrew-tap.sh in onembyte/kolkrabbi.
# Do not edit by hand: regenerate it from the release's own checksums.txt.
class Kolk < Formula
  desc "Model-agnostic AI coding agent for the terminal"
  homepage "https://kolkrabbi.francomichetti.com/"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/onembyte/kolkrabbi/releases/download/v1.3.4/kolk_1.3.4_darwin_arm64.tar.gz"
      sha256 "251b4007f19024b3588e37d95f6ec2dad5573ced0860e6e6b8400c69b3442f9d"
    end
    on_intel do
      url "https://github.com/onembyte/kolkrabbi/releases/download/v1.3.4/kolk_1.3.4_darwin_amd64.tar.gz"
      sha256 "0f34ce21ae4334b1dab548be7213c38f9ddbb26002849e05b6b2d5cbfcdcb2d3"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/onembyte/kolkrabbi/releases/download/v1.3.4/kolk_1.3.4_linux_arm64.tar.gz"
      sha256 "c927a0e842d69fdb51e82f1e3619a609a75085f46500e28a12d51a687ad57993"
    end
    on_intel do
      url "https://github.com/onembyte/kolkrabbi/releases/download/v1.3.4/kolk_1.3.4_linux_amd64.tar.gz"
      sha256 "4ab861f4d75afcbea268760950f75adb0ae6646fc475bb47000998f4b0bbe222"
    end
  end

  def install
    bin.install "kolk"
  end

  test do
    assert_match "kolk", shell_output("#{bin}/kolk help")
  end
end
