# typed: false
# frozen_string_literal: true

# Generated by scripts/update-homebrew-tap.sh in onembyte/kolkrabbi.
# Do not edit by hand: regenerate it from the release's own checksums.txt.
class Kolk < Formula
  desc "Model-agnostic AI coding agent for the terminal"
  homepage "https://kolkrabbi.francomichetti.com/"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/onembyte/kolkrabbi/releases/download/v1.3.5/kolk_1.3.5_darwin_arm64.tar.gz"
      sha256 "8cbcbd4e0acdcfa5647fff92d0ad685b1b5dd05b069ebf379a93dfe6a322f863"
    end
    on_intel do
      url "https://github.com/onembyte/kolkrabbi/releases/download/v1.3.5/kolk_1.3.5_darwin_amd64.tar.gz"
      sha256 "e3745222e67993535103ca7983aa84e11939fae22b4f21c3b71f5da38590ffb0"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/onembyte/kolkrabbi/releases/download/v1.3.5/kolk_1.3.5_linux_arm64.tar.gz"
      sha256 "e9f9461c75044c5f7dea48f6478720df8b84c41e3ca4d9f2e375ea8a386c996f"
    end
    on_intel do
      url "https://github.com/onembyte/kolkrabbi/releases/download/v1.3.5/kolk_1.3.5_linux_amd64.tar.gz"
      sha256 "c035f2a7f314062511bc48e1bac40f632058be3b748db684322c6f6e6abdb49a"
    end
  end

  def install
    bin.install "kolk"
  end

  test do
    assert_match "kolk", shell_output("#{bin}/kolk help")
  end
end
